default: &default 
  adapter: postgresql 
  encoding: unicode 
  pool: 5 
  timeout: 5000
  ##HEROKU
  # Comment the next 4 lines for Heroku
  username: postgres 
  password: <%=ENV['DB_PASSWORD']%>
  host: postgres 
  port: 5432

development: 
  <<: *default 
  database: <%=ENV['DATABASE_NAME']||'app_development'%>

production: 
  <<: *default 
  database: <%=ENV['DATABASE_NAME']||'app_production'%>
  ##HEROKU
  # Unomment the next line for Heroku
  # url: <%= ENV['DATABASE_URL'] %>

test: 
  <<: *default 
  database: app_test